
export const MEMBERS_LOADED = 'MEMBERS_LOADED';
export const MEMBERS_ERROR  = 'MEMBERS_ERROR';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';
export const CATEGORY_ID = 'CATEGORY_ID';
export const POSTS_LOADED = 'POSTS_LOADED';
export const POSTS_ERROR = 'POSTS_LOADED';
